---
- name: Deploy Elasticsearch node1
  hosts: es1
  become: yes
  roles:
    - /Users/yteng/github/e-commerce-sample/devops/remote/roles/elasticsearch
  tags:
    - es
    - "{{ inventory_hostname }}"

- name: Deploy Elasticsearch node2
  hosts: es2
  become: yes
  roles:
    - /Users/yteng/github/e-commerce-sample/devops/remote/roles/elasticsearch
  tags:
    - es
    - "{{ inventory_hostname }}"


- name: Deploy Elasticsearch node3
  hosts: es3
  become: yes
  roles:
    - /Users/yteng/github/e-commerce-sample/devops/remote/roles/elasticsearch
  tags:
    - es
    - "{{ inventory_hostname }}"


- name: Deploy Kibana
  hosts: kibana
  become: yes
  roles:
    - kibana
  tags:
    - kibana

- name: Deploy Logstash
  hosts: logstash
  become: yes
  roles:
    - logstash
  tags:
    - logstash

